---
name: Documentation
description: Found a typo or something that needs clarification?
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: When filing a documentation issue, please include the following information.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's Code of Conduct.
          required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why should we update our documentation?
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: What should we do instead?
    validations:
      required: false
